version: '3.8'
services:
  postgres-14:
    image: postgres:14.1
    ports:
      - "5434:5434"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
    environment:
      POSTGRES_PASSWORD: Pm7xRpwbnUKFQ
      POSTGRES_DB: postal_tracking
  postal-tracking:
    depends_on:
      postgres-14:
        condition: service_healthy
    build: ./
    ports:
      - "8082:8082"
    environment:
      # service port
      server.port: 8082
      spring.datasource.url: jdbc:postgresql://postgres-14/postal_tracking
      spring.datasource.username: postgres
      spring.datasource.password: Pm7xRpwbnUKFQ
      jwt.token.secret: qBTmv4oXFFR2GwjexDJ4t6fsIUIUhhXqlktXjXdkcyygs8nPVEwMfo29VDRRepYDV

