server:
  port: ${server.port}

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: ${spring.datasource.url}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      batch_size: 50
      fetch_size: 50
      hibernate.format_sql: true
      hibernate.default_schema: tracking
    show-sql: false
  liquibase:
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    default-schema: public
    enabled: true

# возможность отключения Spring Security в тестовых целях
security:
  enabled: true

jwt:
  token:
    secret: ${jwt.token.secret}
    expired: 3600000


