server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postal_tracking
    username: postgres
    password: postgres
  jpa:
    show-sql: true
  liquibase:
    enabled: true

security:
  enabled: true

jwt:
  token:
    secret: test-secret-for-app

logging:
  level:
    org:
      springframework:
        security: DEBUG




