--liquibase formatted sql

--changeset vasiliy.sharpf:1
CREATE SCHEMA IF NOT EXISTS tracking;

--changeset vasiliy.sharpf:2
CREATE TABLE tracking.addresses
(
    id             bigint        NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description    varchar(1024) NOT NULL
);

CREATE INDEX idx_addresses_description ON tracking.addresses (description);

--changeset vasiliy.sharpf:3
CREATE TABLE tracking.postal_items
(
    id                    bigint        NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type                  varchar(10)   NOT NULL,
    recipient             varchar(50)   NOT NULL,
    index_of_recipient    varchar(20)   NOT NULL,
    address_of_recipient  bigint        NOT NULL REFERENCES tracking.addresses ("id")
);

--changeset vasiliy.sharpf:4
CREATE TABLE tracking.post_offices
(
    index           varchar(20)   NOT NULL UNIQUE PRIMARY KEY,
    name            varchar(1024) NOT NULL,
    address         bigint        NOT NULL REFERENCES tracking.addresses ("id")
);

--changeset vasiliy.sharpf:5
CREATE TABLE tracking.postage_statuses
(
    postal_item_id   bigint       NOT NULL REFERENCES tracking.postal_items ("id") ON DELETE CASCADE PRIMARY KEY,
    status           varchar(50)  NOT NULL
);

--changeset vasiliy.sharpf:6
CREATE TABLE tracking.postage_events
(
    id               bigint       NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    postal_item_id   bigint       NOT NULL REFERENCES tracking.postal_items ("id"),
    post_office_id   varchar(20)  NOT NULL REFERENCES tracking.post_offices ("index"),
    event_date       timestamp with time zone NOT NULL DEFAULT now(),
    event            varchar(50)  NOT NULL
);

CREATE INDEX idx_postage_events_postal_item_id ON tracking.postage_events (postal_item_id);


