--liquibase formatted sql

--changeset vasiliy.sharpf:1
CREATE TABLE tracking.users
(
    id             bigint        NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username       varchar(100)  NOT NULL UNIQUE,
    first_name     varchar(100)  NOT NULL,
    last_name      varchar(100)  NOT NULL,
    email          varchar(100)  NOT NULL,
    password       varchar(1024)  NOT NULL,
    status         varchar(30)  NOT NULL DEFAULT 'ACTIVE'

);

CREATE INDEX idx_users_username ON tracking.users (username);

--changeset vasiliy.sharpf:2
CREATE TABLE tracking.roles
(
    id                    bigint        NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                  varchar(100)  NOT NULL UNIQUE
);

--changeset vasiliy.sharpf:3
CREATE TABLE tracking.user_roles
(
    user_id         bigint       NOT NULL REFERENCES tracking.users ("id") ON DELETE CASCADE,
    role_id         bigint       NOT NULL REFERENCES tracking.roles ("id") ON DELETE CASCADE
);

CREATE INDEX idx_user_roles_user_id ON tracking.user_roles (user_id);
CREATE INDEX idx_user_roles_role_id ON tracking.user_roles (role_id);
